### ISSUE TITLE
nothing to restore?

### ISSUE THREAD

**Issue by brianmahlstedt** [xplodwild/realmdefensecheat#1]
First of all, awesome work!

I had to change Pa to float64 here: https://github.com/xplodwild/realmdefensecheat/blob/da0bfaeceaba4894ae2553dc9e7b77ad4039f661/src/github.com/xplodwild/realmdefensecheat/realmdefense/api.go#L240.

Whenever I attempt to restore however, it says "Nothing to restore" - any ideas?

**Comment by xplodwild** [comment]
Thanks for the hint about the Pa type, my value was 0 so I assumed it was an int.

You can try the other method mentioned on the Release page, ie. backup your save, then force-quit the game (swipe it from your phone's Recent apps), then run the tool, then open the game. The game will perform what they call a "loadsave" and update your gems.

**Comment by xplodwild** [comment]
The updated version is up, and I recommend using the "kill and restart game" method.
It looks like the Restore button works only if there are substantial changes to the save, for example a different amount of items or heroes level, but otherwise say "Nothing to restore" if only gems changed, for some reason.
I'm closing the issue for now :)
